// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gjzxoetfqlnrrcbcjtka.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdqenhvZXRmcWxucnJjYmNqdGthIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYwNTA0MTMsImV4cCI6MjA5MTYyNjQxM30.giArAJqduNT3XC4iwgik9BDxBumHW88A8Y4RV4kGbQk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});